[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    ; No external libs needed for raw GPIO LEDs

build_flags = 
    -DHOVER_SERIAL_RX=16
    -DHOVER_SERIAL_TX=17

    
    ; --- Display Settings (TFT_eSPI) ---
    -D USER_SETUP_LOADED=1
    
    ; Define Driver (Uncomment/Change if using ST7789 or others)
    ;-D ILI9341_DRIVER=1
    ;-D ILI9341_2_DRIVER=1
    -D ST7735_DRIVER=1
    -D TFT_WIDTH=128
    -D TFT_HEIGHT=128
    -D ST7735_REDTAB=1 
    -D TFT_RGB_ORDER=TFT_BGR 
    
    ; Define Pins
    -D TFT_CS=5
    -D TFT_DC=2
    -D TFT_RST=4
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    
    ; Font & Color Settings
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SMOOTH_FONT=1
    -D SPI_FREQUENCY=10000000


